function [files,logo,web] = dataForDoc()
% This function provides additional data that is necessary to generate the
% documentation


%% Files

proj_dir = fileparts(fileparts(mfilename('fullpath')));

files = {...
	[proj_dir filesep 'src' filesep '@sss'] ,...
	[proj_dir filesep 'src' filesep 'extras'] ,...
    [proj_dir filesep 'src' filesep 'sim'] ,...
    [proj_dir filesep 'demos' filesep 'sss_gettingStarted.m'] ,...
	};


%% Logo

logo = sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s',...
    '%   <td style="background-color:#ffffff; border:0; width:25%; vertical-align:middle; text-align:center">',...
    '%             <img src="img/logo_sss_long.png" alt="sss_Logo" height="40px">',...
    '%      </td>', ...
    '%   <td style="background-color:#ffffff; border:0; width:25%; vertical-align:middle; text-align:center">',...
    '%      <img src="img/Logo_Textzusatz_rechts_engl_Chair.png" alt="RT_Logo" height="40px"></td>', ...
    '%   <td style="background-color:#ffffff; border:0; width:25%; vertical-align:middle; text-align:center">',...
    '%      <img src="img/logoTFD_SR_RGB.png" alt="TFD_Logo" height="40px"></td>', ...
    '%   <td style="background-color:#ffffff; border:0; width:25%; vertical-align:middle; text-align:center">',...
    '%      <img src="img/TUM-logo.png" alt="TUM_Logo" height="40px"></td>');

%% Web

web = sprintf('%s',...
	'%        <a href="https://www.rt.mw.tum.de/?sss">Website</a>');

    